######################################################################
# Automatically generated by qmake (3.0) Tue Apr 21 01:58:11 2015
######################################################################

TEMPLATE = app
TARGET = luks-dictionary
INCLUDEPATH += .:/usr/include

# Input
HEADERS += trydictionary.h
SOURCES += main.cpp trydictionary.cpp
LIBS += -lcryptsetup
